# Pandas for Data Analysis

## Agenda

 - Lab 1: Using pandas plot method to plot graphs from DataFrame
 - Use basic matplotlib to create visualizations

## Data I/O

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


df = pd.read_csv('resources/cars.csv')

In [2]:
df.head()

,symboling,normalized_losses,make,fuel_type,aspiration,num_of_doors,drive_wheels,engine_location,wheel_base,length,...,horsepower,peak_rpm,city_mpg,highway_mpg,price,convertible,hardtop,hatchback,sedan,wagon
0,3,NaN,alfa-romero,gas,std,two,rwd,front,88.6,168.8,...,111.0,5000.0,21,27,13495.0,1,0,0,0,0
1,2,164.0,audi,gas,std,four,fwd,front,99.8,176.6,...,102.0,5500.0,24,30,13950.0,0,0,0,1,0
2,2,164.0,audi,gas,std,four,4wd,front,99.4,176.6,...,115.0,5500.0,18,22,17450.0,0,0,0,1,0
3,2,NaN,audi,gas,std,two,fwd,front,99.8,177.3,...,110.0,5500.0,19,25,15250.0,0,0,0,1,0
4,1,158.0,audi,gas,std,four,fwd,front,105.8,192.7,...,110.0,5500.0,19,25,17710.0,0,0,0,1,0

## Lab 1: Numerical variables analysis

 - Plot a histogram of `price` 
 - Create a new variable, `price_log`, which contains the natural log of `price`
 - Plot a histogram of `price_log` with the following properties:
     - 15 bins
     - edgecolor black
     - xlabel says "log_transform_price"
 - Plot two scatter plots with titles:
     - price vs highway_mpg
     - price_log vs highway_mpg

### Optional

 - Write a function `numerical_plots(df, variable_name)`, which generates a histogram for a value and the log of that value and then use it to get plots for `engine_size` and `engine_size_log`

In [3]:
# Student solution